### ISSUE TITLE
Extension causes validation error for CircleCI config.yml.

### ISSUE THREAD

**Issue by majelbstoat** [GoogleCloudPlatform/cloud-code-vscode#251]
**Environment**:
Extension version: 1.4.0
VSCode version: 1.45.1
OS: darwin

**Description**:

Enabling the CloudCode extension causes issues validating a valid CircleCI config.yml file.

The specific validation issue is:

```Unable to load schema from 'appengine://schema/unknown_item': No content.```

**Repro step**:

1. Create <root>/.circleci/config.yml. A sample CloudCode config looks like: https://circleci.com/docs/2.0/sample-config/
2. Enable the CloudCode extension.
3. Observe the error in Problems.

**Comment by kschaab** [comment]
At the moment we are not supporting AppEngine schema in VS Code.  We need to ignore this since it is not supported.

**Comment by kschaab** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3011)

**Comment by redborian** [comment]
This has been fixed in the latest release.

**Comment by majelbstoat** [comment]
wait, so is this fixed, or not fixed? 😂

for the avoidance of doubt, i'm not using AppEngine, or its schema. I'm using CircleCI.

**Comment by redborian** [comment]
Sorry for the confusion. We do support AppEngine schema now. The schema load error has been fixed. However, we do not support CircleCI schema at this time.
