### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kevinboutin** [GoogleCloudPlatform/cloud-code-vscode#523]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.17.0`
- OS Version: `Darwin x64 21.2.0`
- VS Code version: `1.63.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/3d/mcs_fclj3jg7hlkbqkprdlhm0000gp/T/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[googlecloudtools.cloudcode-unresponsive.cpuprofile.txt](https://github.com/GoogleCloudPlatform/cloud-code-vscode/files/7873165/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt)

**Comment by ssmall** [comment]
Hi @kevinboutin, can you please re-open this issue and attach the CPU profile file so that we can investigate?

**Comment by kevinboutin** [comment]
@ssmall The second link is the cpuprofile.

**Comment by ssmall** [comment]
Apologies, I see that now. I initially mistook it as a continuation of the line above it.

**Comment by kschaab** [comment]
Thanks for reporting this and your profile was super helpful!   We are looking into a fix.

**Comment by browneye1826** [comment]
This issue seems to be getting worse lately...

**Comment by dataod** [comment]
> Cloud SDK was installed but was found to be invalid or corrupted so it was removed. Attempting to reinstall. Managed dependencies will be unavailable during this process. (install attempt 2)

**Comment by ssmall** [comment]
We have pushed a fix for this issue to the [Insiders channel](https://github.com/GoogleCloudPlatform/cloud-code-vscode/wiki/Insiders-Release-Notes#build-march-03-2022) -- please [give it a try](https://cloud.google.com/code/docs/vscode/insiders) and confirm that the issue is resolved.

**Comment by browneye1826** [comment]
Its almost like MSFT is making sure to keep you guys away 🙈
Such a shame, I miss using GCP...

This is on Insiders just now:
![image](https://user-images.githubusercontent.com/59311049/158018016-6be44a70-7534-4eaf-a4c7-061b07ab22d8.png)

<details>
<summary>Sys Info</summary>

![image](https://user-images.githubusercontent.com/59311049/158018085-96da9e07-813d-4221-ad6a-ad2e7534a896.png)

</details>

**Comment by browneye1826** [comment]
Oops, my bad. I thought that by insiders you mean using VS Code 'insiders edition'.
I switched the update channel to Insiders now. So far its looking positive (hallelujah).

**Comment by j-windsor** [comment]
This is fixed in Cloud Code v1.17.1. Thanks for reporting this!

**Comment by MaSven** [comment]
This is not fixed for me. Opening vscode currently leads to 100% CPU usage. I have 1.17.1 installed.
